baseURL = 'https://git4san.github.io'
languageCode = 'en-us'
title = 'SaNs Portfolio'

# Outputs settings
[outputs]
home = ["HTML", "CSS", "RSS", "JSON", "WebAppManifest"]
section = ["HTML", "RSS"]

# Enable SCSS to CSS processing in the Hugo assets pipeline
[imaging]
  quality = 75

# Custom site parameters
[params]
  reading_time = true
